#!/usr/bin/env python3
"""
demo_server - Main entry point
Generated by FastestMCP CLI
"""

import asyncio
import sys
import os

# Add src to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

from src.server import app

async def main():
    """Main execution function"""
    # Run the MCP server
    await app.run_stdio_async()

if __name__ == "__main__":
    asyncio.run(main())
