#!/usr/bin/env python3
"""
demo_client_client - Main entry point
Generated by FastestMCP CLI
"""

import asyncio
import sys
import os

# Add src to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

from src.client import Demo_ClientClient

async def main():
    """Main execution function"""
    client = Demo_ClientClient()

    try:
        await client.connect()

        # Example usage of programmatic APIs
        result = await client.api_endpoint_1(param="example_value")
        print(f"API Result: {result}")

    except Exception as e:
        print(f"❌ Error: {e}")
    finally:
        await client.disconnect()

if __name__ == "__main__":
    asyncio.run(main())
